######################################
#  Direcs and files
######################################

# XXX leading direcs './' ARE IMPORTANT
BASE_DIR := ../../
UMD_BASENAME := makefileforjs
TARGET_DIR := $(BASE_DIR)/dist

TARGETS := $(TARGET_DIR)/$(UMD_BASENAME).min.js \
		   $(TARGET_DIR)/$(UMD_BASENAME).min.js.gz \
	       $(TARGET_DIR)/$(UMD_BASENAME).js \
	       $(TARGET_DIR)/$(UMD_BASENAME).js.gz \

include $(BASE_DIR)/.makefiles/conf.makefile
